"area: apps":
  - all:
      - changed-files:
          - any-glob-to-any-file: "apps/**"
          - all-globs-to-all-files: "!apps/site/src/_pages/**"

"area: apps > site":
  - changed-files:
      - any-glob-to-any-file: "apps/site/**"

"area: blocks":
  - changed-files:
      - any-glob-to-any-file: "blocks/**"

"area: dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "**/patches/**"
          - "**/yarn.lock"

"area: infra":
  - changed-files:
      - any-glob-to-any-file:
          - ".changeset/config.json"
          - ".config/**"
          - ".github/**"
          - ".husky/**"
          - "infra/**"
          - "*"

"area: libs":
  - changed-files:
      - any-glob-to-any-file: "libs/**"

"area: tests":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.ts"
          - "**/tests/**"

"area: user success":
  - changed-files:
      - any-glob-to-any-file:
          - "apps/site/src/_pages/docs/**"
          - "apps/site/src/_pages/spec/**"
          - "apps/site/src/_pages/roadmap/**"
          - "rfcs"

"area: user success > docs":
  - changed-files:
      - any-glob-to-any-file: "apps/site/src/_pages/docs/**"

"area: user success > rfcs":
  - changed-files:
      - any-glob-to-any-file: "rfcs/**"

"area: user success > spec":
  - changed-files:
      - any-glob-to-any-file: "apps/site/src/_pages/spec/**"

"area: libs > @Þ/core":
  - changed-files:
      - any-glob-to-any-file: "libs/@blockprotocol/core/**"

"area: libs > @Þ/design-system":
  - changed-files:
      - any-glob-to-any-file: "libs/@blockprotocol/design-system/**"

"area: libs > @Þ/graph":
  - changed-files:
      - any-glob-to-any-file: "libs/@blockprotocol/graph/**"

"area: libs > @Þ/hook":
  - changed-files:
      - any-glob-to-any-file: "libs/@blockprotocol/hook/**"

"area: libs > @Þ/type-system":
  - changed-files:
      - any-glob-to-any-file:
          - "libs/@blockprotocol/type-system-node/**"
          - "libs/@blockprotocol/type-system-web/**"

"area: libs > @local/*":
  - changed-files:
      - any-glob-to-any-file: "libs/@local/**"

"area: libs > block-scripts":
  - changed-files:
      - any-glob-to-any-file: "libs/block-scripts/**"

"area: libs > block-template-custom-element":
  - changed-files:
      - any-glob-to-any-file: "libs/block-template-custom-element/**"

"area: libs > block-template-html":
  - changed-files:
      - any-glob-to-any-file: "libs/block-template-html/**"

"area: libs > block-template-react":
  - changed-files:
      - any-glob-to-any-file: "libs/block-template-react/**"

"area: libs > blockprotocol":
  - changed-files:
      - any-glob-to-any-file: "libs/blockprotocol/**"

"area: libs > create-block-app":
  - changed-files:
      - any-glob-to-any-file: "libs/create-block-app/**"

"area: libs > mock-block-dock":
  - changed-files:
      - any-glob-to-any-file: "libs/mock-block-dock/**"

"area: libs > wordpress-plugin":
  - changed-files:
      - any-glob-to-any-file: "libs/wordpress-plugin/**"

"type: frontend":
  - changed-files:
      - any-glob-to-any-file: "libs/@blockprotocol/design-system/**"

"type: writing":
  - changed-files:
      - any-glob-to-any-file: "apps/site/src/_pages/**"
