name: Warm-up repo
description: Prepares Node and Yarn dependencies

inputs:
  playwright-deps:
    default: ""
    description: "List of browsers separated by space, e.g. 'chrome firefox'"
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16 ## aligned with Node version on Vercel
        cache: yarn

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: libs/@blockprotocol/type-system/crate

    - name: Install Cargo-Make
      shell: bash
      run: |
        cargo install cargo-quickinstall
        cargo quickinstall cargo-make --version 0.35.15

    - run: yarn install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ inputs.playwright-deps == '' }}

    - run: yarn playwright install-deps ${{ inputs.playwright-deps }}
      if: ${{ inputs.playwright-deps != '' }}
      shell: bash
