name: Warm-up repo
description: Prepares Node and Yarn dependencies

inputs:
  playwright-deps:
    default: ""
    description: "List of browsers separated by space, e.g. 'chrome firefox'"
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: 18 ## aligned with Node version on Vercel

    - name: Install Rust tools
      uses: taiki-e/install-action@e73edba6cef4fb2754007a50e0b28cf1c702c52b # v2.42.40
      with:
        tool: just@1.13.0,wasm-pack@0.11.0

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2
      with:
        workspaces: libs/@blockprotocol/type-system/crate
        shared-key: "shared"

    - run: yarn install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ inputs.playwright-deps == '' }}

    - run: yarn playwright install-deps ${{ inputs.playwright-deps }}
      if: ${{ inputs.playwright-deps != '' }}
      shell: bash
