name: Warm-up repo
description: Prepares Node and Yarn dependencies

inputs:
  playwright-deps:
    default: ""
    description: "List of browsers separated by space, e.g. 'chrome firefox'"
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18 ## aligned with Node version on Vercel

    - name: Install Rust tools
      uses: taiki-e/install-action@v2
      with:
        tool: just@1.13.0,wasm-pack@0.11.0

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: libs/@blockprotocol/type-system/crate
        shared-key: "shared"

    - run: yarn install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ inputs.playwright-deps == '' }}

    - run: yarn playwright install-deps ${{ inputs.playwright-deps }}
      if: ${{ inputs.playwright-deps != '' }}
      shell: bash
