name: Warm-up repo
description: Prepares Node and Yarn dependencies

inputs:
  playwright-deps:
    default: ""
    description: "List of browsers separated by space, e.g. 'chrome firefox'"
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 22 ## aligned with Node version on Vercel

    - name: Install Rust tools
      uses: taiki-e/install-action@e73edba6cef4fb2754007a50e0b28cf1c702c52b # v2.42.40
      with:
        tool: just@1.13.0,wasm-pack@0.11.0

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      with:
        workspaces: libs/@blockprotocol/type-system/crate
        shared-key: "shared"

    - run: yarn install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ inputs.playwright-deps == '' }}

    - run: yarn playwright install-deps ${{ inputs.playwright-deps }}
      if: ${{ inputs.playwright-deps != '' }}
      shell: bash
