name: Attach pull request to Asana task
on: pull_request

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    steps:
      - uses: Asana/create-app-attachment-github-action@latest
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
