name: Fix
on: workflow_dispatch
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.MACHINE_USER_TOKEN }}

      - name: Warm up repo
        uses: ./.github/actions/warm-up-repo

      - name: Fix
        run: yarn fix

      - name: Commit
        run: |
          git config user.name "Block Protocol"
          git config user.email careers@blockprotocol.org
          git add .
          git commit -m '`yarn fix`'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
