name: End to end tests

on:
  deployment_status:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e_tests:
    name: E2E tests
    if: github.event.deployment_status.state == 'success' && endsWith(github.event.deployment_status.environment, 'blockprotocol')
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: ./.github/actions/warm-up-repo
        with:
          playwright-deps: chrome

      - run: yarn playwright install-deps chrome

      - uses: ./.github/actions/warm-up-vercel
        with:
          deployment-base-url: ${{ !contains(github.event.deployment_status.environment, 'production') && github.event.deployment_status.target_url || 'https://blockprotocol.org' }}

      - name: Run Playwright tests
        run: yarn workspace @apps/site playwright test --project=e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ !contains(github.event.deployment_status.environment, 'production') && github.event.deployment_status.target_url || 'https://blockprotocol.org' }}

      - name: Upload artifact playwright-report
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: site-e2e-tests-playwright-report
          path: apps/site/playwright-report
