name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - uses: kachkaev/labeler@0776a679364a9a16110aac8d0f40f5e11009e327
        ## @todo replace with actions/labeler@v4 (or newer) when this PR is merged:
        ## https://github.com/actions/labeler/pull/316
        with:
          dot: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
