name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: kachkaev/labeler@3194b4b6cedfd6d7faad5a7a2dca889293fcff1b
        ## @todo replace with actions/labeler@v3 (or newer) when this PR is merged
        ## https://github.com/actions/labeler/pull/316
        with:
          dot: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
