## Uses a GH worker token so that ‘Version Packages’ PRs trigger downstream workflows (GITHUB_TOKEN-created PRs do not).
## https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'blockprotocol/blockprotocol'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate Vault
        id: secrets
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: dev
          secrets: |
            automation/data/pipelines/hash/dev github_worker_app_id | GITHUB_WORKER_APP_ID ;
            automation/data/pipelines/hash/dev github_worker_app_private_key | GITHUB_WORKER_APP_PRIVATE_KEY ;

      - name: Get token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ steps.secrets.outputs.GITHUB_WORKER_APP_ID }}
          private-key: ${{ steps.secrets.outputs.GITHUB_WORKER_APP_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: ./.github/actions/warm-up-repo

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@c8bada60c408975afd1a20b3db81d6eee6789308 # v1.4.9
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
