name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}

  # Scan mainline, next and `dev/*` trunks to report all findings:
  push:
    branches:
      - main
      - canary
      - dev/*

  schedule:
    - cron: "30 0 1,15 * *" # scheduled for 00:30 UTC on both the 1st and 15th of the month

jobs:
  semgrep:
    name: Scan

    # Change this in the event of future self-hosting of Action runner:
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep@sha256:875ea8c5200ca5938836fa0c155b2220eca8fc83940da1bfa90caf67d73fb0ed

    # Skip any PR created by Dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        name: Check-out Git project source

      - run: semgrep ci --sarif --output=semgrep.sarif
        name: Run Semgrep
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Check SARIF file exists following Semgrep run
        id: sarif_file_check
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2.0.0
        with:
          files: "semgrep.sarif"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@be8b74c09c1778bcdbea38e1a45efea2cb73e18c # v2.26.6
        with:
          sarif_file: semgrep.sarif
        if: always()
